name: Autotag

on:
  workflow_run:
    workflows: ["Deploy static content to Pages"]
    types:
      - completed

permissions:
  contents: write


jobs:
  tag:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Determine version bump
        id: determine_version
        run: |
          # Extract commit messages since the last tag
          git fetch --tags
          last_tag=$(git describe --tags --abbrev=0 --always)
          commits=$(git log $last_tag..HEAD --pretty=format:%s)

          # Determine the version bump based on commit messages
          if [[ $commits == *"#major"* ]]; then
            echo "bump=major" >> $GITHUB_OUTPUT
          elif [[ $commits == *"#minor"* ]]; then
            echo "bump=minor" >> $GITHUB_OUTPUT
          else
            echo "bump=patch" >> $GITHUB_OUTPUT
          fi

      - name: Create tag
        id: create_tag
        run: |
          current_version=$(git describe --tags --abbrev=0 --always)
          current_version=${current_version:1}

          IFS='.' read -ra version_parts <<< "$current_version"

          # Determine the version bump based on commit messages
          bump="${{ steps.determine_version.outputs.bump }}"

          if [[ $bump == "major" ]]; then
            version_parts[0]=$((version_parts[0] + 1))
            version_parts[1]=0
            version_parts[2]=0
          elif [[ $bump == "minor" ]]; then
            version_parts[1]=$((version_parts[1] + 1))
            version_parts[2]=0
          else
            version_parts[2]=$((version_parts[2] + 1))
          fi

          new_version="v${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"

          echo $new_version

          # Create the new tag
          git tag $new_version
          git push origin $new_version