name: HTML Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install HTML Validator
      run: npm install -g html-validate

    - name: Validate HTML files
      run: html-validate "*.html"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        npm init -y
        npm install jest --save-dev

    - name: Create Jest Configuration
      run: echo "{ 'testMatch': ['**/__tests__/**/*.js','**/?(*.)+(spec|test).js]' }" > jest.config.json

    - name: Install Dependencies
      run: |
        npm install --save-dev jest jsdom
        npm install

    - name: Run Jest Tests
      run: npx jest __tests__/
